# This file was generated by GoReleaser. DO NOT EDIT.
cask "notis" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ab70cb0489d37480635392213ada13a6d23dfce878c57b2d41c4c95a59409f3a"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "886dabe5c24719fe32bb252ead1fae5030345926c52dd2e8f19b3e9a480fed83"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b70121fa13f613cbc363cb50f853952707392a1261360e92012a970b1b3df8b"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6f5da077c42c13a0bf0602c656260bd9f8f0df9ef123f9d182f1c80d38103dc"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "notis"
  desc "Notis endpoint agent — route coding-agent traffic through your local Notis gateway"
  homepage "https://notis.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis-gateway"]
    end
  end

  # No zap stanza required

end
