# This file was generated by GoReleaser. DO NOT EDIT.
cask "notis" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1993218d5749294570fe57c10e0165088c2e4c59059b52b3510f7db4b6d723ac"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4bfb82aafe00670e9e3cde761e9893e06fb271acfb792f9ad4abc06a9ea0276"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a3fc6f78822125036e556334c925f72e83c102ef58467795e0265d96638a159"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29336d02b4385e7db5f055b199e01375196cbeac7be3f5ae5476149aa8c1276e"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "notis"
  desc "Notis endpoint agent — route coding-agent traffic through your local Notis gateway"
  homepage "https://notis.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis-gateway"]
    end
  end

  # No zap stanza required

end
