# This file was generated by GoReleaser. DO NOT EDIT.
cask "notis" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "dbbc146e86b172b8c7a145d329e8edd7a857dc0afbca9bee1d8fce0b10b949fa"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "858730de7299cbcd87aa58430a43b7cb57e8b982524fcde1032d0fcddc11565e"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9206cd6db3e65cdb096b3d8c5da54fa4bd1daa847d667bbb5d63dca3095361e"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ff8ac959c46ad8e277cbd79468f700edfba622a61b3b18d21f1902be0021f3a"
      url "https://github.com/notisio/notis-cli/releases/download/v#{version}/notis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "notis"
  desc "Notis endpoint agent — route coding-agent traffic through your local Notis gateway"
  homepage "https://notis.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notis-gateway"]
    end
  end

  # No zap stanza required

end
